### ISSUE TITLE
Bump compatibility to Julia 1

### ISSUE THREAD

**Issue by tclements** [anowacki/Geodesics.jl#2]
I'm trying to add Geodesics as a dependency to my package ([SeisNoise.jl](https://github.com/tclements/SeisNoise.jl)), which requires Julia 1.x. Geodesics is failing to install on Travis CI because of the julia 0.7 in the REQUIRE file.  Could you change your Project.toml to have Julia 1.x compatibility by adding
```
[compat]
julia = "1"
```

**Comment by anowacki** [comment]
Thanks for the suggestion—it's probably good practice to declare Julia compatibility, so I've done this in 73c8344 regardless of the following.

However, I'm not sure the problem is the compatibility bound being undeclared.  I think the real issue is that Geodesics.jl is not registered.  SeisNoise.jl as a registered package can't depend on a package which isn't in the same registry.

I'm happy to register the package (#3), but I think I will have to change the name—I've [been told](https://github.com/JuliaLang/METADATA.jl/pull/19976) it's too general for the package's intended purpose.  I [plan at some point to add these great circle calculations to Geodesy.jl](https://github.com/JuliaGeo/Geodesy.jl/issues/40), which seems a better home for it.

As a workaround for now you can of course just paste the code in your own package.  But that's not so satisfactory I know.
